### ISSUE TITLE
Workflow runs are not working

### ISSUE THREAD

**Issue by IntegerOverfl0w** [grayjay-sources/grayjay-sources.github.io#12]
```
Run tibdex/github-app-token@v2.1.0
Error: Input required and not supplied: app_id
```

It looks like the secrets are not being passed onto workflow runs triggered by pull requests. This may be due to a [github change in 2021](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/).

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target

This means that workflows triggered by `pull_request` do not have access to github secrets. But workflows triggered by `pull_request_target` do. You can apply this fix by changing
```workflow
"on":
  pull_request: null
```
to
```workflow
on:
  pull_request_target:
    types:
      - opened
```

**Comment by Bluscream** [comment]
I was reading that earlier but forgot about it. however, seems like it's still unhappy even with the changes, well

**Comment by IntegerOverfl0w** [comment]
Idk about that, It's still running the old workflow file.
I'll update my branch first and then we'll re-run the workflow

**Comment by Bluscream** [comment]
hmm, now it's not even giving me the options to run the workflows. damnit

**Comment by IntegerOverfl0w** [comment]
My bad, you also need to add synchronize too (otherwise it will only trigger when you open a pull request, not when you add new commits to one)
```
    types:
      - opened
      - synchronize
```

**Comment by IntegerOverfl0w** [comment]
Ok great, `lint` workflow is fixed now but `validate-and-sort` still needs some fixing.

**Comment by IntegerOverfl0w** [comment]
https://github.com/grayjay-sources/grayjay-sources.github.io/blob/9eeb5e1813935bd1cfa8fb10fc12469eed774b88/.github/workflows/sources.yaml#L22C1-L28C1


I think you need to add the `repository` field for `actions/checkout`
```
          ref: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
```

**Comment by Bluscream** [comment]
Thanks, added to both workflows. lets see :D

**Comment by IntegerOverfl0w** [comment]
Thanks, noth workflows now correctly handle secrets.

But now it throws a linter error on the github action file. This belongs in a separate issue so I'll close this one.
```
  .github/workflows/lint-changed.yml:30:76: receiver of object dereference "repo" must be type of object but got "string" [expression]
     |
  30 |           repository: ${{ github.event.pull_request.head.repo.full_name || github.head_ref.repo.full_name || github.ref.repo.full_name }}
  ```
