### ISSUE TITLE
Please add Grayjay plugin pro Herohero plugin

### ISSUE THREAD

**Issue by ThunderHen** [grayjay-sources/grayjay-sources.github.io#16]
Please add Grayjay plugin pro Herohero repo 

Repo  https://github.com/PavelZurek/grayjay-plugin-for-herohero
Install grayjay://plugin/https://pavelzurek.github.io/grayjay-plugin-for-herohero/heroheroConfig.json

**Comment by Bluscream** [comment]
Thanks for bringing this to my attention. It will be added in the next few days

**Comment by Bluscream** [comment]
@ThunderHen added your suggestion. Thanks for letting me know!
